Updated docs
TryCarbonara/trycarbonara.github.io pull request #1
Opened 2023-05-17 16:41 UTC by hayasri

Please review - updated overview pages

2023-05-17 16:52 UTC, saurabh-carbonara requested changes
Please check the formatting comments. Also please delete the `.DS_Store` files from the commit push.

2023-05-17 16:52 UTC, saurabh-carbonara commented on docs/getting-started.md
> +================
Can you please revert the style to using # instead of ===, as this is more of .rst file formatting style.

If we want to change to this formatting style, can you please make sure all the markdown files are updated as same, for using ==== instead of #.

2023-05-17 16:52 UTC, saurabh-carbonara commented on docs/getting-started.md
> +If you're operating bare-metal systems, Trycarbonara provides an agent-based solution to gather and export the necessary data. Learn more about setting up for bare-metal in our [Bare-metal Guide](lin
Can you please add `CPU` here, as we plan to add an additional document for `GPU`?

2023-05-17 16:52 UTC, saurabh-carbonara commented on docs/getting-started.md
> +================
[nit] can you please remove the trailing `=` ?

2023-05-17 16:52 UTC, saurabh-carbonara commented on docs/index.rst
> -.. |logo1| image:: _static/Picture1.png
In case we are not using this resource anymore, please remove the copy from the repo.

2023-05-17 16:52 UTC, saurabh-carbonara commented on docs/index.rst
> +Citations
Nice

2023-05-17 22:05 UTC, saurabh-carbonara commented on docs/methodology.md
> +Embodied Carbon Emissions or [Embedded Emissions](https://en.wikipedia.org/wiki/Embedded_emissions)  is the amount of carbon emitted during the creation and disposal of a hardware device. In order to
extra space

2023-05-18 16:04 UTC, hayasri commented on docs/index.rst
> -.. |logo1| image:: _static/Picture1.png
Can we keep this for now? It might come in handy later.

2023-05-18 17:58 UTC, saurabh-carbonara approved these changes
Thank you for making those changes

2023-05-18 17:59 UTC, merged